# Generated by Django 5.1.5 on 2025-01-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(verbose_name='Row'),
        ),
    ]
