# Generated by Django 5.1.5 on 2025-01-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_seat_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='available',
        ),
    ]
