# Generated by Django 5.1.5 on 2025-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_seat_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
