# Generated by Django 5.1.5 on 2025-01-27 15:23

import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('plot', models.TextField(verbose_name='Plot')),
                ('creation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2025)])),
                ('producer', models.CharField(max_length=50, verbose_name='Producer')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('icon', models.ImageField(upload_to='movies/icons/')),
                ('poster', models.ImageField(upload_to='movies/posters/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
