# Generated by Django 5.1.5 on 2025-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('animation', 'Animation'), ('documentary', 'Documentary')], max_length=50, null=True, verbose_name='Genre'),
        ),
    ]
